"""added guild_id column

Revision ID: 0312d62011f1
Revises: d352e849298a
Create Date: 2021-04-11 21:47:37.237916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0312d62011f1'
down_revision = 'd352e849298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('guild_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'guild_id')
    # ### end Alembic commands ###
