"""switched kwargs column to PickleType

Revision ID: 681a82e895ed
Revises: 7b07d271c269
Create Date: 2021-04-10 17:19:43.215013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681a82e895ed'
down_revision = '7b07d271c269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
