"""modified tasks table

Revision ID: 7b07d271c269
Revises: 928c6c9f3646
Create Date: 2021-04-10 17:16:14.802803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b07d271c269'
down_revision = '928c6c9f3646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
