"""Added tasks table

Revision ID: 928c6c9f3646
Revises: 
Create Date: 2021-04-10 16:29:55.507148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928c6c9f3646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('function', sa.String(length=60), nullable=False),
    sa.Column('kwargs', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
