"""added user_id column

Revision ID: d352e849298a
Revises: 681a82e895ed
Create Date: 2021-04-11 21:21:01.454955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd352e849298a'
down_revision = '681a82e895ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'kwargs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('kwargs', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
